In [1]:


import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("powerplant_data.csv")

In [3]:
data.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB

In [5]:
data.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [6]:
data.describe()

                AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [7]:
x=data.drop("PE",axis=1)
y=data["PE"]

In [8]:
#split our data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [9]:
from sklearn.preprocessing import StandardScaler

In [29]:
scaler=StandardScaler()
x_train_scaler=scaler.fit_transform(x_train)
x_test_scaler=scaler.transform(x_test)

In [30]:
x_train_scaler

array([[-1.71269637, -1.04514402,  1.49558946,  0.96375075],
       [-0.80906663, -0.8909988 , -0.96965459,  1.05438161],
       [ 0.15346638,  0.37126182, -0.1259708 ,  0.80995293],
       ...,
       [-0.21601778, -0.83516048,  0.36167844, -0.84543342],
       [ 0.95267669,  1.14198793, -0.42294749, -0.46437186],
       [-1.76892222, -1.19063824,  1.91405662,  0.90882296]],
      shape=(6697, 4))

In [31]:
import torch
import torch.nn as nn

In [32]:
x_train_tensor=torch.tensor(x_train_scaler,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train.values,dtype=torch.float32).view(-1,1)

x_test_tensor=torch.tensor(x_test_scaler,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.float32).view(-1,1)

In [33]:
from torch.utils.data import TensorDataset,DataLoader
train_dataset=TensorDataset(x_train_tensor,y_train_tensor)
test_dataset=TensorDataset(x_test_tensor,y_test_tensor)

In [36]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32)

In [41]:
# build ANN
class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()
        self.model=nn.Sequential(
        # 1st layer
            nn.Linear(x_train.shape[1],6),
            nn.ReLU(),

            nn.Linear(6,6),
            nn.ReLU(),

            nn.Linear(6,1),  
        
        )

    def forward(self,x):
        return self.model(x)

In [44]:
import torch.optim as optim
model=ANN()
# loss , optimizer
crietrion=nn.MSELoss()
optimizer=optim.Adam(model.parameters())

In [54]:
# Train the ANN
train_losses = []
val_losses = []

best_val_loss = float("inf")

epochs = 100

for epoch in range(epochs):
    model.train()
    running_loss = 0.0 # tot training loss for 1 epoch
    
    for xb, yb in train_loader:
        # xb = features of 1 batch
        # yb = labels of 1 batch
        optimizer.zero_grad()
        
        outputs = model(xb) # forward prop....predicted outputs for this batch
        loss = crietrion(outputs, yb) # compute loss
        loss.backward() # back prop.. compute gradients
        optimizer.step() # params update
        
        running_loss += loss.item() # loss is a tensor => py float

    epoch_train_loss = running_loss / len(train_loader)
    train_losses.append(epoch_train_loss)


    # Validation
    model.eval()
    running_val_loss = 0.0

    with torch.no_grad(): # no gradients compute
        for xb, yb in test_loader:
            outputs = model(xb)
            loss = crietrion(outputs, yb)
            running_val_loss += loss

    epoch_val_loss = running_val_loss / len(test_loader)
    val_losses.append(epoch_val_loss)

    print(f"epoch {epoch+1}/{epochs} ==> train loss = {epoch_train_loss} & val loss = {epoch_val_loss}")

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        torch.save(model.state_dict(), "best_model.pt") #.pt or .pth

epoch 1/100 ==> train loss = 772.1067862374442 & val loss = 754.712646484375
epoch 2/100 ==> train loss = 770.7480430966332 & val loss = 748.83447265625
epoch 3/100 ==> train loss = 762.5612354096912 & val loss = 741.5755004882812
epoch 4/100 ==> train loss = 754.1482529413132 & val loss = 732.0489501953125
epoch 5/100 ==> train loss = 745.9975728352864 & val loss = 724.0869140625
epoch 6/100 ==> train loss = 736.1856206984747 & val loss = 714.3355102539062
epoch 7/100 ==> train loss = 727.2978800455729 & val loss = 705.1324462890625
epoch 8/100 ==> train loss = 718.0355478922526 & val loss = 693.6168212890625
epoch 9/100 ==> train loss = 707.2470575241815 & val loss = 680.292724609375
epoch 10/100 ==> train loss = 691.6961616152809 & val loss = 667.2587890625
epoch 11/100 ==> train loss = 678.557694498698 & val loss = 652.293701171875
epoch 12/100 ==> train loss = 662.4197458902995 & val loss = 637.1104736328125
epoch 13/100 ==> train loss = 646.29185660226 & val loss = 620.8487548828125
epoch 14/100 ==> train loss = 628.2175712948754 & val loss = 603.4124755859375
epoch 15/100 ==> train loss = 607.7539015997024 & val loss = 583.5390014648438
epoch 16/100 ==> train loss = 588.4187335786365 & val loss = 562.3487548828125
epoch 17/100 ==> train loss = 564.820553661528 & val loss = 540.2734985351562
epoch 18/100 ==> train loss = 542.935082644508 & val loss = 518.176513671875
epoch 19/100 ==> train loss = 518.7277294340588 & val loss = 492.7143249511719
epoch 20/100 ==> train loss = 493.7068197341192 & val loss = 468.1864929199219
epoch 21/100 ==> train loss = 467.975884719122 & val loss = 441.5227966308594
epoch 22/100 ==> train loss = 439.29505949474515 & val loss = 413.9172668457031
epoch 23/100 ==> train loss = 412.46695287795296 & val loss = 386.83935546875
epoch 24/100 ==> train loss = 383.1363712855748 & val loss = 358.70550537109375
epoch 25/100 ==> train loss = 354.99576277959915 & val loss = 330.4192810058594
epoch 26/100 ==> train loss = 325.35514987763906 & val loss = 303.8231201171875
epoch 27/100 ==> train loss = 297.48404984247117 & val loss = 275.7424011230469
epoch 28/100 ==> train loss = 270.6524677094959 & val loss = 249.39097595214844
epoch 29/100 ==> train loss = 244.41157135736375 & val loss = 225.04824829101562
epoch 30/100 ==> train loss = 220.1064083644322 & val loss = 201.54898071289062
epoch 31/100 ==> train loss = 197.27041531517392 & val loss = 180.499755859375
epoch 32/100 ==> train loss = 177.00110321044923 & val loss = 161.1988983154297
epoch 33/100 ==> train loss = 157.90725658961705 & val loss = 144.3612823486328
epoch 34/100 ==> train loss = 141.12361099606468 & val loss = 129.3429718017578
epoch 35/100 ==> train loss = 128.18566905430384 & val loss = 117.16670227050781
epoch 36/100 ==> train loss = 115.39621622903006 & val loss = 106.51557159423828
epoch 37/100 ==> train loss = 105.71246214367095 & val loss = 98.04277038574219
epoch 38/100 ==> train loss = 98.34023001534598 & val loss = 90.9312515258789
epoch 39/100 ==> train loss = 91.25829370589483 & val loss = 85.33255004882812
epoch 40/100 ==> train loss = 86.26739914303734 & val loss = 80.92158508300781
epoch 41/100 ==> train loss = 82.05358782268706 & val loss = 77.14124298095703
epoch 42/100 ==> train loss = 78.5272867384411 & val loss = 73.64341735839844
epoch 43/100 ==> train loss = 75.37224107469831 & val loss = 70.73180389404297
epoch 44/100 ==> train loss = 72.1636221840268 & val loss = 68.14048767089844
epoch 45/100 ==> train loss = 69.5338464373634 & val loss = 65.49851989746094
epoch 46/100 ==> train loss = 66.9030238015311 & val loss = 63.136837005615234
epoch 47/100 ==> train loss = 64.34402662004743 & val loss = 60.64329528808594
epoch 48/100 ==> train loss = 61.680499848865324 & val loss = 58.02616500854492
epoch 49/100 ==> train loss = 59.085455240522116 & val loss = 55.44248962402344
epoch 50/100 ==> train loss = 56.81295455750965 & val loss = 52.84514617919922
epoch 51/100 ==> train loss = 53.81525023324149 & val loss = 50.33868408203125
epoch 52/100 ==> train loss = 51.15880545661563 & val loss = 47.66910934448242
epoch 53/100 ==> train loss = 48.309990065438406 & val loss = 44.90821838378906
epoch 54/100 ==> train loss = 45.61924789973668 & val loss = 42.33210372924805
epoch 55/100 ==> train loss = 42.97668765840076 & val loss = 39.668704986572266
epoch 56/100 ==> train loss = 40.191588047572544 & val loss = 37.09957504272461
epoch 57/100 ==> train loss = 37.642160701751706 & val loss = 34.6775016784668
epoch 58/100 ==> train loss = 35.18879579816546 & val loss = 32.317039489746094
epoch 59/100 ==> train loss = 32.93461798713321 & val loss = 30.270233154296875
epoch 60/100 ==> train loss = 30.79380721137637 & val loss = 28.21632194519043
epoch 61/100 ==> train loss = 28.984220295860652 & val loss = 26.6109561920166
epoch 62/100 ==> train loss = 27.201373717898413 & val loss = 25.009693145751953
epoch 63/100 ==> train loss = 25.785824376060848 & val loss = 23.80423927307129
epoch 64/100 ==> train loss = 24.57409806478591 & val loss = 22.718793869018555
epoch 65/100 ==> train loss = 23.59692424138387 & val loss = 21.89110565185547
epoch 66/100 ==> train loss = 22.85765300478254 & val loss = 21.30095100402832
epoch 67/100 ==> train loss = 22.31870149884905 & val loss = 20.77204704284668
epoch 68/100 ==> train loss = 21.843749141693117 & val loss = 20.51449966430664
epoch 69/100 ==> train loss = 21.60138666743324 & val loss = 20.27968406677246
epoch 70/100 ==> train loss = 21.374665205819266 & val loss = 20.153003692626953
epoch 71/100 ==> train loss = 21.2884983698527 & val loss = 20.093420028686523
epoch 72/100 ==> train loss = 21.207241103762673 & val loss = 20.03167152404785
epoch 73/100 ==> train loss = 21.128730991908483 & val loss = 20.04990005493164
epoch 74/100 ==> train loss = 21.087719217936197 & val loss = 20.01155662536621
epoch 75/100 ==> train loss = 21.125203523181735 & val loss = 20.03139877319336
epoch 76/100 ==> train loss = 21.201328718094597 & val loss = 20.002641677856445
epoch 77/100 ==> train loss = 21.12512585776193 & val loss = 20.031633377075195
epoch 78/100 ==> train loss = 21.184155146280926 & val loss = 20.01259994506836
epoch 79/100 ==> train loss = 21.118405541919525 & val loss = 20.078125
epoch 80/100 ==> train loss = 21.20868917646862 & val loss = 20.051382064819336
epoch 81/100 ==> train loss = 21.14113556543986 & val loss = 20.021303176879883
epoch 82/100 ==> train loss = 21.137525908152263 & val loss = 20.043031692504883
epoch 83/100 ==> train loss = 21.20771414893014 & val loss = 20.03105926513672
epoch 84/100 ==> train loss = 21.366136382874988 & val loss = 20.067371368408203
epoch 85/100 ==> train loss = 21.238181441170827 & val loss = 20.06398582458496
epoch 86/100 ==> train loss = 21.15991402126494 & val loss = 20.08060646057129
epoch 87/100 ==> train loss = 21.24050530024937 & val loss = 20.067716598510742
epoch 88/100 ==> train loss = 21.228743925548734 & val loss = 20.254039764404297
epoch 89/100 ==> train loss = 21.237301676613942 & val loss = 20.228260040283203
epoch 90/100 ==> train loss = 21.16996175675165 & val loss = 20.01886558532715
epoch 91/100 ==> train loss = 21.22222464879354 & val loss = 20.13941192626953
epoch 92/100 ==> train loss = 21.623721149989535 & val loss = 20.422409057617188
epoch 93/100 ==> train loss = 21.268905875796364 & val loss = 20.055883407592773
epoch 94/100 ==> train loss = 21.30540252867199 & val loss = 20.30348777770996
epoch 95/100 ==> train loss = 21.31719118754069 & val loss = 20.253734588623047
epoch 96/100 ==> train loss = 21.28032506306966 & val loss = 20.31194305419922
epoch 97/100 ==> train loss = 21.340609055473692 & val loss = 20.020315170288086
epoch 98/100 ==> train loss = 21.320363489786782 & val loss = 20.107065200805664
epoch 99/100 ==> train loss = 21.25228078932989 & val loss = 20.045392990112305
epoch 100/100 ==> train loss = 21.30348035267421 & val loss = 20.126611709594727

In [49]:
# !pip install matplotlib
# import matplotlib.pyplot as plt

# loss_df = pd.DataFrame({
#     "Training Loss": train_losses,
#     "Validation Loss": val_losses
# })

# plt.plot(loss_df["Training Loss"], label = "Training Loss")
# plt.plot(loss_df["Validation Loss"], label = "Validation Loss")

# plt.xlabel("Epochs")
# plt.ylabel("Losses")

# plt.legend()

In [50]:
model.load_state_dict(torch.load("best_model.pt"))

In [55]:
# Evaluation

model.eval()
with torch.no_grad():
    train_preds = model(x_train_tensor)
    test_preds = model(x_test_tensor)

    train_mse_loss = crietrion(train_preds, y_train_tensor)
    test_mse_loss = crietrion(test_preds, y_test_tensor)

print("Training MSE:", train_mse_loss.item())
print("Testing MSE:", test_mse_loss.item())

Training MSE: 21.139684677124023
Testing MSE: 20.0948543548584

In [56]:
from sklearn.metrics import r2_score

print("r^2 score =", r2_score(y_test, test_preds))

r^2 score = 0.9302182058442701